const intertwinedFateImg = "https://static.wikia.nocookie.net/gensin-impact/images/1/1f/Item_Intertwined_Fate.png";

const GenshinCharacters = {
  "1" : {
    name: "Amber",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Pyro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: "https://static.wikia.nocookie.net/gensin-impact/images/f/ff/Amber_Card.png",
  },
  "2" : {
    name: "Barbara",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Hydro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: "https://static.wikia.nocookie.net/gensin-impact/images/9/92/Barbara_Introduction_Card.png",
  },
  "3" : {
    name: "Beidou",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Electro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: "https://static.wikia.nocookie.net/gensin-impact/images/d/d9/Beidou_Introduction_Card.png",
  },
  "4" : {
    name: "Bennett",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Pyro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "5" : {
    name: "Chongyun",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Cryo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "6" : {
    name: "Diluc",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Pyro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "7" : {
    name: "Fischl",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Electro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "8" : {
    name: "Jean",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Anemo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "9" : {
    name: "Kaeya",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Cryo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "10" : {
    name: "Keqing",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Electro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "11" : {
    name: "Klee",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Pyro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "12" : {
    name: "Lisa",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Electro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "13" : {
    name: "Mona",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Hydro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "14" : {
    name: "Ningguang",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Geo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "15" : {
    name: "Noelle",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Geo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "16" : {
    name: "Qiqi",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Cryo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "17" : {
    name: "Razor",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Electro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "18" : {
    name: "Sucrose",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "19" : {
    name: "Traveler",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "None",
    nation: "None",
    description: "Description Coming Soon",
    image: "https://static.wikia.nocookie.net/gensin-impact/images/0/0a/Traveler_Introduction_Card.png",
  },
  "20" : {
    name: "Venti",
    version: "1.0",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Anemo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
 "21" : {
    name: "Xiangling",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Pyro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"22" : {
    name: "Xingqiu",
    version: "1.0",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Hydro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"23" : {
    name: "Diona",
    version: "1.1",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Cryo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"24" : {
    name: "Tartaglia",
    version: "1.1",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Hydro",
    nation: "Snezhnaya",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"25" : {
    name: "Xinyan",
    version: "1.1",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Pyro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"26" : {
    name: "Zhongli",
    version: "1.1",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Geo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"27" : {
    name: "Albedo",
    version: "1.2",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Geo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"28" : {
    name: "Ganyu",
    version: "1.2",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Cryo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"29" : {
    name: "Hu Tao",
    version: "1.3",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Pyro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"30" : {
    name: "Xiao",
    version: "1.3",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Anemo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "31" : {
    name: "Rosaria",
    version: "1.4",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Cryo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"32" : {
    name: "Eula",
    version: "1.5",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Cryo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"33" : {
    name: "Yanfei",
    version: "1.5",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Pyro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"34" : {
    name: "Kaedehara Kazuha",
    version: "1.6",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Anemo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"35" : {
    name: "Kamisato Ayaka",
    version: "2.0",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Cryo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"36" : {
    name: "Sayu",
    version: "2.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Anemo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"37" : {
    name: "Yoimiya",
    version: "2.0",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Pyro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"38" : {
    name: "Aloy",
    version: "2.1",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Cryo",
    nation: "None",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"39" : {
    name: "Kujou Sara",
    version: "2.1",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Electro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
"40" : {
    name: "Raiden Shogun",
    version: "2.1",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Electro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "41" : {
    name: "Sangonomiya Kokomi",
    version: "2.1",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Hydro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "42" : {
    name: "Thoma",
    version: "2.2",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Pyro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "43" : {
    name: "Arataki Itto",
    version: "2.3",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Geo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "44" : {
    name: "Gorou",
    version: "2.3",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Geo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "45" : {
    name: "Shenhe",
    version: "2.4",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Cryo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "46" : {
    name: "Yun Jin",
    version: "2.4",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Geo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "47" : {
    name: "Yae Miko",
    version: "2.5",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Electro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "48" : {
    name: "Kamisato Ayato",
    version: "2.6",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Hydro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "49" : {
    name: "Kuki Shinobu",
    version: "2.7",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Electro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "50" : {
    name: "Yelan",
    version: "2.7",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Hydro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "51" : {
    name: "Shikanoin Heizou",
    version: "2.8",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "52" : {
    name: "Collei",
    version: "3.0",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Dendro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "53" : {
    name: "Dori",
    version: "3.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Electro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "54" : {
    name: "Tighnari",
    version: "3.0",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Dendro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "55" : {
    name: "Candace",
    version: "3.1",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Hydro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "56" : {
    name: "Cyno",
    version: "3.1",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Electro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "57" : {
    name: "Nilou",
    version: "3.1",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Hydro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "58" : {
    name: "Layla",
    version: "3.2",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Cryo",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "59" : {
    name: "Nahida",
    version: "3.2",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Dendro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "60" : {
    name: "Faruzan",
    version: "3.3",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Anemo",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "61" : {
    name: "Wanderer",
    version: "3.3",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "62" : {
    name: "Alhaitham",
    version: "3.4",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Dendro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "63" : {
    name: "Yaoyao",
    version: "3.4",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Dendro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "64" : {
    name: "Dehya",
    version: "3.5",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Pyro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "65" : {
    name: "Mika",
    version: "3.5",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Cryo",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "66" : {
    name: "Baizhu",
    version: "3.6",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Dendro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "67" : {
    name: "Kaveh",
    version: "3.6",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Dendro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "68" : {
    name: "Kirara",
    version: "3.7",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Dendro",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "69" : {
    name: "Freminet",
    version: "4.0",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Cryo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "70" : {
    name: "Lynette",
    version: "4.0",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Anemo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "71" : {
    name: "Lyney",
    version: "4.0",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Pyro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "72" : {
    name: "Neuvillette",
    version: "4.1",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Hydro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "73" : {
    name: "Wriothesley",
    version: "4.1",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Cryo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "74" : {
    name: "Charlotte",
    version: "4.2",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Cryo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "75" : {
    name: "Furina",
    version: "4.2",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Hydro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "76" : {
    name: "Chevreuse",
    version: "4.3",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Pyro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "77" : {
    name: "Navia",
    version: "4.3",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Geo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "78" : {
    name: "Gaming",
    version: "4.4",
    rarity: "4 Stars",
    weapon: "Claymore",
    element: "Pyro",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "79" : {
    name: "Xianyun",
    version: "4.4",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "80" : {
    name: "Chiori",
    version: "4.5",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Geo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "81" : {
    name: "Arlecchino",
    version: "4.6",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Pyro",
    nation: "Snezhnaya",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "82" : {
    name: "Clorinde",
    version: "4.7",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Electro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "83" : {
    name: "Sethos",
    version: "4.7",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Electro",
    nation: "Sumeru",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "84" : {
    name: "Sigewinne",
    version: "4.7",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Hydro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "85" : {
    name: "Emilie",
    version: "4.8",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Dendro",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "86" : {
    name: "Kachina",
    version: "5.0",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Geo",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "87" : {
    name: "Kinich",
    version: "5.0",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Dendro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "88" : {
    name: "Mualani",
    version: "5.0",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Hydro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "89" : {
    name: "Xilonen",
    version: "5.1",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Geo",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "90" : {
    name: "Chasca",
    version: "5.2",
    rarity: "5 Stars",
    weapon: "Bow",
    element: "Anemo",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "91" : {
    name: "Ororon",
    version: "5.2",
    rarity: "4 Stars",
    weapon: "Bow",
    element: "Electro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "92" : {
    name: "Citlali",
    version: "5.3",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Cryo",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "93" : {
    name: "Lan Yan",
    version: "5.3",
    rarity: "4 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Liyue",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "94" : {
    name: "Mavuika",
    version: "5.3",
    rarity: "5 Stars",
    weapon: "Claymore",
    element: "Pyro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "95" : {
    name: "Yumemizuki Mizuki",
    version: "5.4",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Inazuma",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "96" : {
    name: "Iansan",
    version: "5.5",
    rarity: "4 Stars",
    weapon: "Polearm",
    element: "Electro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "97" : {
    name: "Varesa",
    version: "5.5",
    rarity: "5 Stars",
    weapon: "Catalyst",
    element: "Electro",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "98" : {
    name: "Escoffier",
    version: "5.6",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Cryo",
    nation: "Fontaine",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "99" : {
    name: "Ifa",
    version: "5.6",
    rarity: "4 stars",
    weapon: "Catalyst",
    element: "Anemo",
    nation: "Natlan",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "100" : {
    name: "Skirk",
    version: "5.7",
    rarity: "5 Stars",
    weapon: "Sword",
    element: "Cryo",
    nation: "",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "101" : {
    name: "Dahlia",
    version: "5.7",
    rarity: "4 Stars",
    weapon: "Sword",
    element: "Hydro",
    nation: "Mondstadt",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
  "102" : {
    name: "Ineffa",
    version: "5.8",
    rarity: "5 Stars",
    weapon: "Polearm",
    element: "Electro",
    nation: "Nod-Krai",
    description: "Description Coming Soon",
    image: intertwinedFateImg,
  },
};

export { GenshinCharacters };
