const SpecialPassImg = "https://static.wikia.nocookie.net/houkai-star-rail/images/a/a7/Item_Star_Rail_Special_Pass.png";

const HonkaiStarRailCharacters = {
  "1" : {
    name:  "Arlan",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Destruction",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "2" : {
    name:  "Asta",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Harmony",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "3" : {
    name:  "Bailu",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Abundance",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "4" : {
    name:  "Bronya",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "5" : {
    name:  "Clara",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "6" : {
    name:  "Dan Heng",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "The Hunt",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "7" : {
    name:  "Gepard",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Preservation",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "8" : {
    name:  "Herta",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Erudition",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "9" : {
    name:  "Himeko",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "10" : {
    name:  "Hook",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Destruction",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "11" : {
    name:  "Jing Yuan",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "12" : {
    name:  "March 7th",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Preservation",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "13" : {
    name:  "Natasha",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Abundance",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "14" : {
    name:  "Pela",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Nihility",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "15" : {
    name:  "Qingque",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Erudition",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "16" : {
    name:  "Sampo",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Nihility",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "17" : {
    name:  "Seele",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "18" : {
    name:  "Serval",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Erudition",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "19" : {
    name:  "Sushang",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "The Hunt",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "20" : {
    name:  "Tingyun",
    version: "1.0",
    rarity: "4 Star",
    weapon: "",
    path: "Harmony",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "21" : {
    name:  "Trailblazer",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "22" : {
    name:  "Trailblazer",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Preservation",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "23" : {
    name:  "Welt",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "24" : {
    name:  "Yanqing",
    version: "1.0",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "25" : {
    name:  "Luocha",
    version: "1.1",
    rarity: "5 Star",
    weapon: "",
    path: "Abundance",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "26" : {
    name:  "Silver Wolf",
    version: "1.1",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "27" : {
    name:  "Yukong",
    version: "1.1",
    rarity: "4 Star",
    weapon: "",
    path: "Harmony",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "28" : {
    name:  "Blade",
    version: "1.2",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "29" : {
    name:  "Kafka",
    version: "1.2",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "30" : {
    name:  "Luka",
    version: "1.2",
    rarity: "4 Star",
    weapon: "",
    path: "Nihility",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "31" : {
    name:  "Fu Xuan",
    version: "1.3",
    rarity: "5 Star",
    weapon: "",
    path: "Preservation",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "32" : {
    name:  "Lynx",
    version: "1.3",
    rarity: "4 Star",
    weapon: "",
    path: "Abundance",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "33" : {
    name:  "Guinaifen",
    version: "1.4",
    rarity: "4 Star",
    weapon: "",
    path: "Nihility",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "34" : {
    name:  "Topaz & Numby",
    version: "1.4",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "35" : {
    name:  "Jingliu",
    version: "1.4",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "36" : {
    name:  "Argenti",
    version: "1.5",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "37" : {
    name:  "Hanya",
    version: "1.5",
    rarity: "4 Star",
    weapon: "",
    path: "Harmony",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "38" : {
    name:  "Huohuo",
    version: "1.5",
    rarity: "5 Star",
    weapon: "",
    path: "Abundance",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "39" : {
    name:  "Dr. Ratio",
    version: "1.6",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "40" : {
    name:  "Ruan Mei",
    version: "1.6",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "41" : {
    name:  "Xueyi",
    version: "1.6",
    rarity: "4 Star",
    weapon: "",
    path: "Destruction",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "42" : {
    name:  "Black Swan",
    version: "2.0",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "43" : {
    name:  "Misha",
    version: "2.0",
    rarity: "4 Star",
    weapon: "",
    path: "Destruction",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "44" : {
    name:  "Sparkle",
    version: "2.0",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "45" : {
    name:  "Acheron",
    version: "2.1",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "46" : {
    name:  "Aventurine",
    version: "2.1",
    rarity: "5 Star",
    weapon: "",
    path: "Preservation",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "47" : {
    name:  "Gallagher",
    version: "2.1",
    rarity: "4 Star",
    weapon: "",
    path: "Abundance",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "48" : {
    name:  "Boothill",
    version: "2.2",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "49" : {
    name:  "Robin",
    version: "2.2",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "50" : {
    name:  "Trailblazer",
    version: "2.2",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "51" : {
    name:  "Firefly",
    version: "2.3",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "52" : {
    name:  "Jade",
    version: "2.3",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "53" : {
    name:  "Jiaoqiu",
    version: "2.4",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "54" : {
    name:  "Yunli",
    version: "2.4",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "55" : {
    name:  "Feixiao",
    version: "2.5",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "56" : {
    name:  "Lingsha",
    version: "2.5",
    rarity: "5 Star",
    weapon: "",
    path: "Abundance",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "57" : {
    name:  "Moze",
    version: "2.5",
    rarity: "4 Star",
    weapon: "",
    path: "The Hunt",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "58" : {
    name:  "Rappa",
    version: "2.6",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "59" : {
    name:  "Fugue",
    version: "2.7",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Fire",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "60" : {
    name:  "Sunday",
    version: "2.7",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "61" : {
    name:  "Aglaea",
    version: "3.0",
    rarity: "5 Star",
    weapon: "",
    path: "Remembrance",
    type: "Lightning",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "62" : {
    name:  "The Herta",
    version: "3.0",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "63" : {
    name:  "Trailblazer",
    version: "3.0",
    rarity: "5 Star",
    weapon: "",
    path: "Remembrance",
    type: "Ice",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "64" : {
    name:  "Mydei",
    version: "3.1",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Imaginary",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "65" : {
    name:  "Tribbie",
    version: "3.1",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "66" : {
    name:  "Castorice",
    version: "3.2",
    rarity: "5 Star",
    weapon: "",
    path: "Remembrance",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
   "67" : {
    name:  "Anaxa",
    version: "3.2",
    rarity: "5 Star",
    weapon: "",
    path: "Erudition",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "68" : {
    name:  "Cipher",
    version: "3.3",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "69" : {  
    name:  "Hyacine",
    version: "3.3",
    rarity: "5 Star",
    weapon: "",
    path: "Remembrance",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "70" : {  
    name:  "Archer",
    version: "3.4",
    rarity: "5 Star",
    weapon: "",
    path: "The Hunt",
    type: "Quantum",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "71" : {  
    name:  "Phainon",
    version: "3.4",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "72" : {  
    name:  "Saber",
    version: "3.4",
    rarity: "5 Star",
    weapon: "",
    path: "Destruction",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "73" : {  
    name:  "Cerydra",
    version: "",
    rarity: "5 Star",
    weapon: "",
    path: "Harmony",
    type: "Wind",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  },
  "74" : {  
    name:  "Hysilens",
    version: "",
    rarity: "5 Star",
    weapon: "",
    path: "Nihility",
    type: "Physical",
    world: "",
    description: "Description Coming Soon",
    image: SpecialPassImg,
  }
};

export { HonkaiStarRailCharacters };
