const RadiantTideImg = "https://static.wikia.nocookie.net/wutheringwaves/images/f/f0/Item_Radiant_Tide.png";

const WutheringWavesCharacters = {
   "1" : {
    name:  "Aalto",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Pistol",
    attribute: "Aero",
    region: "The Black Shores",
    faction: "Black Shores",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "2" : {
    name:  "Baizhi",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Rectifier",
    attribute: "Glacio",
    region: "Huanglong",
    faction: "Huaxu Academy",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "3" : {
    name:  "Calcharo",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Broadblade",
    attribute: "Electro",
    region: "Huanglong",
    faction: "Ghost Hounds",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "4" : {
    name:  "Chixia",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Pistol",
    attribute: "Fusion",
    region: "Huanglong",
    faction: "Public Security Bureau",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "5" : {
    name:  "Danjin",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Sword",
    attribute: "Havoc",
    region: "Huanglong",
    faction: "Midnight Rangers",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "6" : {
    name:  "Encore",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Fusion",
    region: "The Black Shores",
    faction: "Black Shores",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "7" : {
    name:  "Jianxin",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Aero",
    region: "Huanglong",
    faction: "Fengyiquan",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "8" : {
    name:  "Jiyan",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Broadblade",
    attribute: "Aero",
    region: "Huanglong",
    faction: "Midnight Rangers",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "9" : {
    name:  "Lingyang",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Glacio",
    region: "Huanglong",
    faction: "Liondance Troupe",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "10" : {
    name:  "Mortefi",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Pistol",
    attribute: "Fusion",
    region: "Huanglong",
    faction: "Huaxu Academy",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "11" : {
    name:  "Verina",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Spectro",
    region: "Huanglong",
    faction: "Pioneer Association",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "12" : {
    name:  "Rover-Havoc",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Havoc",
    region: "The Black Shores",
    faction: "Arbiters",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "13" : {
    name:  "Rover-Spectro",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Spectro",
    region: "The Black Shores",
    faction: "Arbiters",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "14" : {
    name:  "Sanhua",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Sword",
    attribute: "Glacio",
    region: "Huanglong",
    faction: "City Hall",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "15" : {
    name:  "Yangyang",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Sword",
    attribute: "Aero",
    region: "Huanglong",
    faction: "Midnight Rangers",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "16" : {
    name:  "Yinlin",
    version: "1.0",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Electro",
    region: "Huanglong",
    faction: "Public Security Bureau",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "17" : {
    name:  "Yuanwu",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Gauntlet",
    attribute: "Electro",
    region: "Huanglong",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "18" : {
    name:  "Taoqi",
    version: "1.0",
    rarity: "4 Star",
    weapon: "Broadblade",
    attribute: "Havoc",
    region: "Huanglong",
    faction: "Ministry of Development",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "19" : {
    name:  "Changli",
    version: "1.1",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Fusion",
    region: "Huanglong",
    faction: "City Hall",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "20" : {
    name:  "Jinhsi",
    version: "1.1",
    rarity: "5 Star",
    weapon: "Broadblade",
    attribute: "Spectro",
    region: "Huanglong",
    faction: "City Hall",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "21" : {
    name:  "Xiangli Yao",
    version: "1.2",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Electro",
    region: "Huanglong",
    faction: "Huaxu Academy",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "22" : {
    name:  "Zhezhi",
    version: "1.2",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Glacio",
    region: "Huanglong",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "23" : {
    name:  "Youhu",
    version: "1.3",
    rarity: "4 Star",
    weapon: "Gauntlet",
    attribute: "Glacio",
    region: "Huanglong",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "24" : {
    name:  "The Shorekeeper",
    version: "1.3",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Spectro",
    region: "The Black Shores",
    faction: "Black Shores",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "25" : {
    name:  "Camellya",
    version: "1.4",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Havoc",
    region: "The Black Shores",
    faction: "Black Shores",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "26" : {
    name:  "Lumi",
    version: "1.4",
    rarity: "4 Star",
    weapon: "Broadblade",
    attribute: "Electro",
    region: "Huanglong",
    faction: "Lollo Logistics",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "27" : {
    name:  "Carlotta",
    version: "2.0",
    rarity: "5 Star",
    weapon: "Pistol",
    attribute: "Glacio",
    region: "Rinascita",
    faction: "Montelli Family",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "28" : {
    name:  "Roccia",
    version: "2.0",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Havoc",
    region: "Rinascita",
    faction: "Troupe of Fools Acquired",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "29" : {
    name:  "Brant",
    version: "2.1",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Fusion",
    region: "Rinascita",
    faction: "Troupe of Fools",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "30" : {
    name:  "Phoebe",
    version: "2.1",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Spectro",
    region: "Rinascita",
    faction: "Order of the Deep",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "31" : {
    name:  "Cantarella",
    version: "2.2",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Havoc",
    region: "Rinascita",
    faction: "Fisalia Family",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "32" : {
    name:  "Rover-Aero",
    version: "2.2",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Aero",
    region: "The Black Shores",
    faction: "Arbiters",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "33" : {
    name:  "Ciaccona",
    version: "2.3",
    rarity: "5 Star",
    weapon: "Pistol",
    attribute: "Aero",
    region: "Rinascita",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "34" : {
    name:  "Zani",
    version: "2.3",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Spectro",
    region: "Rinascita",
    faction: "Montelli Family",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "35" : {
    name:  "Cartethyia",
    version: "2.4",
    rarity: "5 Star",
    weapon: "Sword",
    attribute: "Aero",
    region: "Rinascita",
    faction: "Order of the Deep",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "36" : {
    name:  "Lupa",
    version: "2.4",
    rarity: "5 Star",
    weapon: "Broadblade",
    attribute: "Fusion",
    region: "Septimont",
    faction: "House Silva",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "37" : {
    name:  "Phrolova",
    version: "2.5",
    rarity: "5 Star",
    weapon: "Rectifier",
    attribute: "Havoc",
    region: "",
    faction: "Fractsidus",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "38" : {
    name:  "Iuno",
    version: "2.6",
    rarity: "5 Star",
    weapon: "Gauntlet",
    attribute: "Aero",
    region: "Septimont",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  },
   "39" : {
    name:  "Augusta",
    version: "2.6",
    rarity: "5 Star",
    weapon: "Broadblade",
    attribute: "Electro",
    region: "Septimont",
    faction: "",
    description: "Description Coming Soon",
    image: RadiantTideImg,
  }
};

export { WutheringWavesCharacters };